### ISSUE TITLE
NPE in VirtualMachineImpl.computerName

### ISSUE THREAD

**Issue by puneet101** [Azure-Samples/compute-java-manage-vm#11]
java.lang.NullPointerException
    at com.microsoft.azure.management.compute.implementation.VirtualMachineImpl.computerName(VirtualMachineImpl.java:735)

Looks like when a custom OS disk is added to a new VM, it may not have a computer name.

Sample VM:
## Computer name

Status
Running

Operating system
Windows

Location
Central US

**Comment by anuchandy** [comment]
thanks @puneet101, will get this fixed

**Comment by anuchandy** [comment]
created a PR with this fix, will be merged in couple of days.

**Comment by anuchandy** [comment]
in master, closing this.
